task Intro-1
js-tasks-ru/htmlcss-20210114_danil4 pull request #1
Opened 2021-01-14 14:01 UTC by Danil-eg

add *Hello World!*

2021-01-14 14:13 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Hello world
+ вводная задача
```

Добавляю преподавателя (@Thewhiterabbit123) для код-ревью, посмотрим что он скажет :)

2021-01-14 15:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @Thewhiterabbit123

2021-01-14 19:31 UTC, Thewhiterabbit123 commented
Привет! Рада приветствовать тебя на курсе)
Что-то пошло не так и в решение не попал файл со стилями) Добавь, пожалуйста

2021-01-14 19:32 UTC, Thewhiterabbit123 requested changes

2021-01-14 19:32 UTC, Thewhiterabbit123 commented on 01-intro/01-hello-world/solution.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Расскажешь для чего эти 2 тега? `meta`

2021-01-26 16:32 UTC, Thewhiterabbit123 requested changes

2021-01-26 16:32 UTC, Thewhiterabbit123 commented on 03-lection1/01-button/button.css
> +	background-color: transparent;
Все-таки тут белый цвет фона)

2021-01-26 16:32 UTC, Thewhiterabbit123 commented on 03-lection1/01-button/button.css
> +.btn-group > *:not(:last-child) {
Достаточно сложный селектор, может сделать элемент для `.btn-group` и примиксовать к кнопкам?

2021-02-24 14:21 UTC, PDmitryA commented on 03-lection1/02-accordion/index.html
> +<<<<<<< HEAD
от конфликта осталось, надо убрать эти пометки git

2021-02-24 14:34 UTC, PDmitryA approved these changes

2021-02-24 14:34 UTC, PDmitryA commented on 03-lection1/01-button/button.css
> +    transition: all .5s ease-out;
лучше не делать `transition: all`, так как анимируются все свойства -> даже те, что анимируются плохо -> может лагать на слабых (и не только) устройствах

2021-02-24 14:34 UTC, PDmitryA commented on 04-lection2/01-histogram/histogram.css
> +.histogram__head-total {
не нужна тут ссылка, minor
<img width="1349" alt="Screen Shot 2021-02-24 at 17 32 51" src="https://user-images.githubusercontent.com/22381017/109015584-5402bd80-76c6-11eb-93d9-0c1b3a42faae.png">

2021-02-24 14:34 UTC, PDmitryA commented
оставленные комменты - на будущее

2021-02-24 14:34 UTC, merged